### Required for AAD to used Managed Identity to be able to deployed elastic cluster.

apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: ps-de-managed-ident-cdie-binding
spec:
  azureIdentity: ps-de-managed-ident-cdie-identity
  selector: ps-de-managed-ident-cdie