apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rolebinding
  namespace: elastic-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: optimized-cluster-role
subjects:
- namespace: webapps 
  kind: ServiceAccount
  name: elasticagent