name: scale-down-at-5pm

on:
  workflow_dispatch:
  schedule:
  - cron: '00 23 * * *'

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: gke-informatica-containers
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: infaagent-bq
  NAMESPACE: secure-agent-test
  RUNTIME_ENV: container_bq_test

jobs:
  docker:
    name: "Build secure agent docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/493022562702/locations/global/workloadIdentityPools/secure-agent-id-pool/providers/sa-provider'
          service_account: 'gh-deployer@secure-agent-container.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

    # Get the GKE credentials so we can deploy to the cluster
      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      
      # Deploy sample image to the GKE cluster
      - name: Deploy
        run: |-
          kubectl scale --replicas=1 deployment/$DEPLOYMENT_NAME --namespace secure-agent-test